version: '3'

services:
  gameserver-service:
    image: moneygames/test-service:alpha
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
  vis:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8069:8080"
    deploy:
      placement:
        constraints: [ node.role == manager ]
